development:
 secret_key_base: f5e292a298741f80f060ca9c21e928fd4ad94283e2281b85e0a5d6bab559678bbc33b46d9ac54d64da32a3297c0445fff9cef1a01e375841e22b9b9cc47ce38e
 facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
 facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
 secret_key_base: f5e292a298741f80f060ca9c21e928fd4ad94283e2281b85e0a5d6bab559678bbc33b46d9ac54d64da32a3297c0445fff9cef1a01e375841e22b9b9cc47ce38e
 facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
 facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

production:
 secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
 facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
 facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>